(setq n 5)

(defun calcula_pi(novo_n d bool)
    (if (> novo_n n)
        (return-from calcula_pi 0)
    )
    (if (= bool 0)
	(- (/ 4 d) (calcula_pi (+ novo_n 1) (+ d 2) 0))
	(+ (/ 4 d) (calcula_pi (+ novo_n 1) (+ d 2) 1))
    )
)

(if (< n 1)
    (print (nil))
    (print (float (calcula_pi 1 1 0)))
)
