version: '3'
services:
  master:
    build:
      context: .
      dockerfile: DockerfileMaster
  slave:
    build:
      context: .
      dockerfile: DockerfileSlave

    depends_on:
      - master

